// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package biz.buildit.main;

import biz.buildit.main.WorksEngineer;
import javax.persistence.Entity;

privileged aspect WorksEngineer_Roo_Jpa_Entity {
    
    declare @type: WorksEngineer: @Entity;
    
}
